
dic_prescricao = {'Ameaça': 3, 'Infanticídio': 12, "Lesão Corporal": 4,
                  "Lesão Grave": 12, "Lesão Gravíssima": 12, "Homicídio simples": 20,
                  "Homicídio qualificado": 20, "Feminicídio": 20, "Homicídio culposo": 8,
                  "Induzimento, instigação ou auxílio a suicídio ou a automutilação": 4, "Calunia": 4,
                  "Difamação": 3, "Injúria": 3, "Abandono de incapaz": 8,
                  "Abandono de incapaz com resultado de lesão grave": 12,
                  "Abandono de incapaz  com resultado de lesão grave": 20, "Exposição ou abandono de recém-nascido": 4,
                  "Exposição ou abandono de recém-nascido com lesão grave": 8,
                  "Exposição ou abandono de recém-nascido com morte": 12,
                  "Omissão de socorro": 3, "Omissão de socorro com lesão grave": 3, "Omissão de socorro com morte": 4,
                  "Condicionamento de atendimento médico-hospitalar emergencial": 3, "Maus tratos": 4,
                  "Maus tratos com lesão grave": 8,
                  "Maus tratos com morte": 16, "Rixa": 3, "Rixa com morte ou lesão grave": 4, "Injúria Racial": 8,
                  "Constrangimento ilegal": 3,
                  "Perseguição": 4, "Perseguição majorada": 8, "Violência psicológica contra a mulher": 4,
                  "Sequestro e cárcere privado": 8, "Sequestro e cárcere privado majorado": 12,
                  "Sequestro e cárcere privado com grave sofrimento físico ou moral": 12,
                  "Redução a condição análoga à de escravo": 12, "Redução a condição análoga à de escravo majorado": 16,
                  "Tráfico de Pessoas": 12, "Tráfico de pessoas majorado": 16, "Violação de domicílio": 3,
                  "Violação de domicílio majorado": 4, "Violação de correspondência": 3,
                  "Sonegação ou destruição de correspondência": 3, "Divulgação de segredo": 3, "Divulgação de informações sigilosas da Administração Pública": 8,
                  "Violação do segredo profissional": 3, "Invasão de dispostitivo informático": 8, "Furto": 8,
                  "Furto durante repouso noturno": 12, "Furto qualificado": 12, "Furto com emprego de explosivo": 16,
                  "Furto mediante fraude e por meio de dispositivo eletrônico ou informático": 12, "Furto de veículo automotor com transporte interestadual":12,
                  "Furto de semovente": 12, "Furto de substância explosiva": 16, "Furto de coisa comum": 4,
                  "Roubo": 16, "Roubo majorado": 16, "Latrocínio": 20, "Extorsão": 16, "Extorsão mediante sequestro": 20,
                  "Extorsão indireta": 8, "Dano": 3, "Dano qualificado": 8, "Apropriação Indébita": 8, "Apropriação Indébita Previdenciária": 12,
                  "Estelionato": 8, "Estelionato Eletrônico": 12, "Abuso de Incapazes": 12, "Receptação": 8, "Receptação qualificada": 12,
                  "Receptação de animal": 12, "Estupro": 16, "Violação sexual mediante fraude": 12, "Importunação sexual": 12,
                  "Assédio Sexual": 4, "Registro não autorizado da intimidade sexual": 3, "Estupro de vulnerável": 20, "Corrupção de menores": 12,
                  "Satisfação de lascívia mediante presença de criança ou adolescente": 8,
                  "Favorecimento da prostituição ou de outra forma de exploração sexual de criança ou adolescente ou de vulnerável" : 16,
                  "Divulgação de cena de estupro": 12, "Divulgação de cena de estupro majorada": 12,
                  "Mediação para servir a lascívia de outrem": 8, "Mediação para servir a lascívia de outrem contra vítima menor": 12,
                  "Mediação para servir a lascívia de outrem com violência": 12,
                  "Favorecimento da prostituição": 12, "Casa de prostituição": 12, "Rufianismo": 8, "Rufianismo contra vítima menor": 12,
                  "Rufianismo com violência": 12, "Ato obsceno": 3, "Escrito obseceno": 4, "Bigamia": 12, "Registro de nascimento inexistente": 12,
                  "Parto suposto": 12, "Sonegação de estado de filiação": 12, "Abandono material": 8, "Entrega de filho menor a pessoa inidônea": 4,
                  "Abandono intelectual": 3, "Induzimento a fuga, entrega arbitrária ou sonegação de incapazes": 3, "Subtração de incapazes": 4,
                  "Incêndio": 12, "Explosão": 12, "Incitação ao crime": 3, "Apologia de crime": 3, "Associação criminosa": 8, "Constituição de milicia privada": 12,
                  "Falsificação de documento público": 12, "Falsificação de documento particular": 12, "Falsidade ideológica": 12, "Falsidade de atestado médico": 3,
                  "Fraudes em certames de interesse público": 8, "Fraudes em certames de interesse público com dano à administração": 12, "Peculato": 20, "Peculato culposo": 3,
                  "Peculato mediante erro de outrem": 8, "Inserção de dados falsos em sistema de informações": 20, "Modificação ou alteração não autorizada de sistema de informações": 4,
                  "Extravio, sonegaçãoo ou inutilização de livro ou documento": 8, "emprego irregular de verbas públicas": 3, "Concussão": 20, "Corrupção passiva": 20,
                  "Facilitação de contrabando ou descaminho": 12, "Prevaricação" :3, "Condescendência criminosa": 3}
lista = [item for item in dic_prescricao]
print(lista)