
dic_prescricao = {'Ameaça': 3, 'Infanticídio': 12, "Lesão Corporal": 4,
                  "Lesão Grave": 12, "Lesão Gravíssima": 12, "Homicídio simples": 20,
                  "Homicídio qualificado": 20, "Feminicídio": 20, "Homicídio culposo": 8,
                  "Induzimento, instigação ou auxílio a suicídio ou a automutilação": 4, "Calunia": 4,
                  "Difamação": 3, "Injúria": 3, "Abandono de incapaz": 8,
                  "Abandono de incapaz com resultado de lesão grave": 12,
                  "Abandono de incapaz  com resultado de lesão grave": 20, "Exposição ou abandono de recém-nascido": 4,
                  "Exposição ou abandono de recém-nascido com lesão grave": 8,
                  "Exposição ou abandono de recém-nascido com morte": 12,
                  "Omissão de socorro": 3, "Omissão de socorro com lesão grave": 3, "Omissão de socorro com morte": 4,
                  "Condicionamento de atendimento médico-hospitalar emergencial": 3, "Maus tratos": 4,
                  "Maus tratos com lesão grave": 8,
                  "Maus tratos com morte": 16, "Rixa": 3, "Rixa com morte ou lesão grave": 4, "Injúria Racial": 8,
                  "Constrangimento ilegal": 3,
                  "Perseguição": 4, "Perseguição majorada": 8, "Violência psicológica contra a mulher": 4,
                  "Sequestro e cárcere privado": 8, "Sequestro e cárcere privado majorado": 12,
                  "Sequestro e cárcere privado com grave sofrimento físico ou moral": 12,
                  "Redução a condição análoga à de escravo": 12, "Redução a condição análoga à de escravo majorado": 16,
                  "Tráfico de Pessoas": 12, "Tráfico de pessoas majorado": 16, "Violação de domicílio": 3,
                  "Violação de domicílio majorado": 4, "Violação de correspondência": 3,
                  "Sonegação ou destruição de correspondência": 3, "Divulgação de segredo": 3, "Divulgação de informações sigilosas da Administração Pública": 8,
                  "Violação do segredo profissional": 3, "Invasão de dispostitivo informático": 8, "Furto": 8,
                  "Furto durante repouso noturno": 12, "Furto qualificado": 12, "Furto com emprego de explosivo": 16,
                  "Furto mediante fraude e por meio de dispositivo eletrônico ou informático": 12, "Furto de veículo automotor com transporte interestadual":12,
                  "Furto de semovente": 12, "Furto de substância explosiva": 16, "Furto de coisa comum": 4,
                  "Roubo": 16, "Roubo majorado": 16, "Latrocínio": 20, "Extorsão": 16, "Extyorsão mediante sequestro": 20,
                  "Extrosão indireta": 8
                  }
lista = [item for item in dic_prescricao]
print(lista)